MFU.WebAPI/Controllers/Apis/DocumentCategorysController.cs
using System;
using System.Collections.Generic;
using System.Web.Http;
using MFU.Models;
using MFU.Service;
using MFU.Models.ValidationRules;
using System.Web.Mvc;

namespace MFU.WebAPI.Controllers
{
    public class DocumentCategorysController : BaseApiController
    {
        private DocumentCategoryService documentCategoryService = new DocumentCategoryService();

        public DocumentCategorysController()
        {
        }

        // GET api/documentCategorys
        public IEnumerable<DocumentCategory> Get()
        {
            return documentCategoryService.GetAll();
        }

        // GET api/documentCategorys/5
        public DocumentCategory Get(int id)
        {
            return documentCategoryService.GetById(id);
        }

        public IHttpActionResult Put(int id, DocumentCategory documentCategory)
        {
            ValidateModel<DocumentCategory>(documentCategory, new DocumentCategoryValidator());
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != documentCategory.Id)
            {
                return BadRequest();
            }

            documentCategoryService.Update(documentCategory);
            return Ok(documentCategory);
        }

        public IHttpActionResult Post(DocumentCategory documentCategory)
        {
            ValidateModel<DocumentCategory>(documentCategory, new DocumentCategoryValidator());

            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            documentCategoryService.Insert(documentCategory);
            return Ok();
        }

        public IHttpActionResult Delete(int id)
        {
            var documentCategory = documentCategoryService.GetById(id);
            if (documentCategory == null)
            {
                return NotFound();
            }

            documentCategoryService.Delete(documentCategory);

            return Ok(documentCategory);
        }
    }
}

MFU.WebAPI/Controllers/HomeController.cs
using MFU.Models;
using MFU.Models.ValidationRules;
using MFU.Service;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace MFU.WebAPI.Controllers
{
    public class HomeController : BaseController
    {
        private DocumentCategoryService documentCategoryService;
        
        public HomeController()
        {
            documentCategoryService = new DocumentCategoryService(); 
        }
        public ActionResult ChangeLanguage(string lang)
        {
            CultureInfo ci = new CultureInfo(lang);
            Thread.CurrentThread.CurrentCulture = ci;
            Thread.CurrentThread.CurrentUICulture = CultureInfo.CreateSpecificCulture(ci.Name);

            HttpCookie cookie = new HttpCookie("Language");
            cookie.Value = lang;
            Response.Cookies.Add(cookie);
            return RedirectToAction("Index");
        }

        public ActionResult Index()
        {
            ViewBag.Title = "Home Page";
            //var documentCategorys = documentCategoryService.GetAll();
            var documentCategorys = new List<DocumentCategory>();
            return View(documentCategorys);
        }

        public ActionResult Details(int id)
        {
            return View(documentCategoryService.GetById(id));
        }

        public ActionResult Create()
        {
            DocumentCategory documentCategory = new DocumentCategory();
            documentCategory.CreatedDate = DateTime.Now;
            documentCategory.ModifiedDate = DateTime.Now;

            return View(documentCategory);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DocumentCategory documentCategory)
        {
            documentCategory.Id = int.MaxValue;
            ValidateModel<DocumentCategory>(documentCategory, new DocumentCategoryValidator());
            if (ModelState.IsValid)
            {
                documentCategoryService.Insert(documentCategory);
                return RedirectToAction("Index");
            }

            return View(documentCategory);
        }

        public ActionResult Edit(int id)
        {
            return View(documentCategoryService.GetById(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, DocumentCategory documentCategory)
        {
            try
            {
                ValidateModel<DocumentCategory>(documentCategory, new DocumentCategoryValidator());
                if (!ModelState.IsValid)
                {
                    return View();
                }

                var oldDocumentCategory = documentCategoryService.GetById(id);
                if (oldDocumentCategory == null)
                {
                    return View();
                }

                documentCategoryService.Update(documentCategory);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            return View(documentCategoryService.GetById(id));
        }

        [HttpPost]
        public ActionResult Delete(int id, DocumentCategory documentCategory)
        {
            try
            {
                documentCategory = documentCategoryService.GetById(id);
                if (documentCategory == null)
                {
                    return View();
                }

                documentCategoryService.Delete(documentCategory);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult ListDropdown()
        {
            return View();
        }
    }
}

MFU.WebAPI/Views/Home/Create.cshtml
@model MFU.Models.DocumentCategory

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DocumentCategory</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModifiedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModifiedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModifiedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MFU.WebAPI/Views/Home/Delete.cshtml
@model MFU.Models.DocumentCategory

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DocumentCategory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MFU.WebAPI/Views/Home/Details.cshtml
@model MFU.Models.DocumentCategory

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>DocumentCategory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MFU.WebAPI/Views/Home/Edit.cshtml
@model MFU.Models.DocumentCategory

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DocumentCategory</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModifiedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModifiedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModifiedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MFU.WebAPI/Views/Home/Index.cshtml
@model IEnumerable<MFU.Models.DocumentCategory>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @System.Globalization.CultureInfo.CurrentCulture.Name
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ModifiedDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

MFU.WebAPI/Views/Home/ListDropdown.cshtml
@model IEnumerable<MFU.Models.DocumentCategory>
@{
    ViewBag.Title = "ListDropdown";
}

<h2>List Dropdown Document Category</h2>

<select class="form-control" id="documentCategorySelect">
    <option value="">--- Select Document Category ---</option> 
</select>
<input type="button" id="btnAddList" value="Add List" class="btn btn-primary" />
<br />
<br />
<table class="table table-bordered" id="documentCategoryTables">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
    </tr>
    <tbody></tbody>
</table>
@section scripts {
    <script type="text/javascript">

        $(document).ready(function () {
            LoadDropdownList = function () {
                $.ajax({
                    type: 'GET',
                    url: '@Url.Action("Get", "DocumentCategorys", new { httproute = "DefaultApi" })',
                    dataType: 'json',
                    success: function (documentCategorys) {
                        $.each(documentCategorys, function (i, documentCategory) {
                            $("#documentCategorySelect").append('<option value="'
                            + documentCategory.id + '">'
                            + documentCategory.name + '</option>');
                        });
                    },
                    error: function (ex) {
                        alert('Failed to retrieve states.' + ex);
                    }
                });
            };

            $("#btnAddList").click(function () {
                if ($("#documentCategorySelect").val() == "")
                    return;

                var selectedId = $("#documentCategorySelect").val();
                $('#documentCategoryTables > tbody:last-child').append(
                    '<tr><td>' + $("#documentCategorySelect").val() + '</td><td>' + $("#documentCategorySelect :selected").text() + '</td></tr>'
                );
                $("#documentCategorySelect option[value='" + selectedId + "']").remove();
            });

            LoadDropdownList();
        });

    </script>
}